# Generated by Django 5.2.8 on 2025-11-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT sin puntos y con guión', max_length=12, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('prevision', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
