# Generated by Django 5.2.8 on 2025-11-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=10, help_text='Stock mínimo para alertas')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('rol', models.CharField(choices=[('MEDICO', 'Médico'), ('ADMIN', 'Administrativo'), ('GERENCIA', 'Gerencia')], max_length=10)),
                ('especialidad', models.CharField(blank=True, help_text='Solo si el rol es Médico', max_length=100, null=True)),
            ],
        ),
    ]
