# Generated by Django 5.2.8 on 2025-11-14 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_medico', models.CharField(default='Centro Principal', max_length=200)),
                ('especialidad', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='AGENDADA', max_length=10)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente')),
            ],
        ),
    ]
