# Generated by Django 5.2.8 on 2025-11-14 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agendamiento.cita')),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('receta_medica', models.TextField(blank=True, help_text='Receta generada', null=True)),
                ('examenes_solicitados', models.TextField(blank=True, help_text='Exámenes solicitados', null=True)),
                ('derivacion', models.TextField(blank=True, help_text='Derivación a especialista', null=True)),
            ],
        ),
    ]
